### ISSUE TITLE
ld: framework not found FFmpeg occur while importing DJIWidget 

### ISSUE THREAD

**Issue by EonKid** [dji-sdk/Mobile-UXSDK-iOS#66]
I am working on DJI iOS sdk based drone app. I updated to latest version 4.9 for DJI Widget .I am able to run my project using DJI-SDK-iOS 4.9.1 but i tried to import DJI Widget version 4.9 into my project getting following errors for my project and sample code provided by you on github:

"ld: framework not found FFmpeg
clang: error: linker command failed with exit code 1 (use -v to see invocation)
"

-  Steps to reproduce the bug or crash issues(It would be great if you can provide this)
-  Crash logs (If you can find it, it would be very helpful)
-  DJI iOS UXSDK 4.9
-  DJI Product Spark
-  iOS 12
-  iOS iPhone SE
-  Xcode 10.1
-  Are you using UXSDK Sample Code (Yes/No)?
   No
-  If the answer of previous one is No, please specify which elements of UXSDK are you using.

#### Is this issue about DJI Android UXSDK and Sample Code?

Then this is the wrong place, please refer to the Mobile-UXSDK-iOS Github: <https://github.com/dji-sdk/Mobile-UXSDK-Android/issues>

![Screenshot 2019-03-09 at 2 28 56 PM](https://user-images.githubusercontent.com/13067085/54068922-c7138f00-4277-11e9-86f8-786cbab6e065.png)

**Comment by EonKid** [comment]
@oliverou Please help me .

**Comment by nacho-carnicero** [comment]
@EonKid I did solve this by including `"${PODS_ROOT}/DJIWidget/FFmpeg"` to the path list under the **Framework search paths** in the **Build settings** menu of your project. You'll need to add it to both debug and release.
Let me know if you don't know how to do this, I'll upload some screen shots.

@oliverou I think this should be updated on the sample code (at least the ObjC one) since I got the same error

**Comment by india2sarthak** [comment]
@nacho-carnicero Thanks works!

**Comment by UnknownWarning** [comment]
Thx @nacho-carnicero. It works.

**Comment by alzin** [comment]
@india2sarthak Thank you
